# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ab644bf5d4348d4269717bbcd6703e6352c1243a8b5fc307a48a6ac5cc6feec133b7c10acca1820651ec2734f4be12fed0f9ec0b5b60690a0dc61b8221a5e82

test:
  secret_key_base: 81108467d7c669600d9cba4ac52c26b84e7071f1b32e54403ca12b2ed6487042a1c8f421ce4cc4699297f16f7245a782ffa385a7cf8b125f4c7a2f409b721d1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
